"""init_users_companies_applications

Revision ID: 1169813f8b54
Revises:
Create Date: 2026-08-30 19:33:56.941487

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1169813f8b54"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_id"), "companies", ["id"], unique=False)
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("role_title", sa.String(length=255), nullable=False),
        sa.Column("jd_text", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "APPLIED",
                "REFERRAL",
                "INTERVIEW",
                "OFFER",
                "REJECTED",
                name="application_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "REFERRAL",
                "COLD",
                "JOB_BOARD",
                name="application_source_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("applied_date", sa.Date(), nullable=True),
        sa.Column("resume_version", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "company_id", "role_title", name="uq_user_company_role"
        ),
    )
    op.create_index(
        op.f("ix_applications_applied_date"),
        "applications",
        ["applied_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_company_id"), "applications", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_applications_id"), "applications", ["id"], unique=False)
    op.create_index(
        op.f("ix_applications_status"), "applications", ["status"], unique=False
    )
    op.create_index(
        "ix_applications_status_applied_date",
        "applications",
        ["status", "applied_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index("ix_applications_status_applied_date", table_name="applications")
    op.drop_index(op.f("ix_applications_status"), table_name="applications")
    op.drop_index(op.f("ix_applications_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_company_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_applied_date"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_id"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
