"""add_contacts_outreach_interview_rounds

Revision ID: 4296911ab259
Revises: 1169813f8b54
Create Date: 2026-08-30 20:50:32.015197

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4296911ab259"
down_revision: str | None = "1169813f8b54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "relation",
            sa.Enum(
                "ALUM",
                "REFERRER",
                "RECRUITER",
                "OTHER",
                name="contact_relation_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("last_contacted_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contacts_application_id"), "contacts", ["application_id"], unique=False
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_table(
        "interview_rounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column(
            "round_type",
            sa.Enum(
                "PHONE_SCREEN",
                "TECH",
                "SYSTEM_DESIGN",
                "HR",
                "BEHAVIORAL",
                name="round_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_date", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "PENDING",
                "PASSED",
                "FAILED",
                name="round_outcome_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_rounds_application_id"),
        "interview_rounds",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_rounds_id"), "interview_rounds", ["id"], unique=False
    )
    op.create_table(
        "outreach_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("message_sent", sa.Text(), nullable=False),
        sa.Column("date_sent", sa.Date(), nullable=False),
        sa.Column("response_received", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outreach_logs_contact_id"),
        "outreach_logs",
        ["contact_id"],
        unique=False,
    )
    op.create_index(op.f("ix_outreach_logs_id"), "outreach_logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outreach_logs_id"), table_name="outreach_logs")
    op.drop_index(op.f("ix_outreach_logs_contact_id"), table_name="outreach_logs")
    op.drop_table("outreach_logs")
    op.drop_index(op.f("ix_interview_rounds_id"), table_name="interview_rounds")
    op.drop_index(
        op.f("ix_interview_rounds_application_id"), table_name="interview_rounds"
    )
    op.drop_table("interview_rounds")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_application_id"), table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###
