"""add_ai_prep_notes_table

Revision ID: dd9b38a4827f
Revises: 4296911ab259
Create Date: 2026-08-30 22:30:03.655692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9b38a4827f'
down_revision: Union[str, None] = '4296911ab259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prep_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('generated_questions', sa.JSON(), nullable=False),
    sa.Column('suggested_bullets', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_prep_notes_application_id'), 'ai_prep_notes', ['application_id'], unique=True)
    op.create_index(op.f('ix_ai_prep_notes_id'), 'ai_prep_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_prep_notes_id'), table_name='ai_prep_notes')
    op.drop_index(op.f('ix_ai_prep_notes_application_id'), table_name='ai_prep_notes')
    op.drop_table('ai_prep_notes')
    # ### end Alembic commands ###
